Repository vanvalenlab/deepcell-spots, pull requests merged in 2024-01, with the labels that each got.

#83 Remove deprecated parameter from training script
  deepcell_spots/training.py
Labels: fix

#84 Update spot detection model to SpotDetection-8
  deepcell_spots/applications/spot_detection.py
Labels: enhancement

#85 Update model name for SpotDetection-8
  deepcell_spots/applications/spot_detection.py
Labels: fix

#86 Fix building/deployment of Python package and docker image
  .github/workflows/docker-image.yaml
  .github/workflows/package.yaml
  .github/workflows/pypi.yaml
  .github/workflows/tests.yaml
  Dockerfile
  requirements.txt
  setup.py
Labels: chore

#88 Prepare for 0.4.1 release
  README.md
  deepcell_spots/__init__.py
  deepcell_spots/_version.py
  deepcell_spots/applications/__init__.py
  deepcell_spots/applications/polaris.py
  deepcell_spots/applications/polaris_test.py
  deepcell_spots/applications/spot_decoding.py
  deepcell_spots/applications/spot_decoding_test.py
  deepcell_spots/applications/spot_detection.py
  deepcell_spots/applications/spot_detection_test.py
  deepcell_spots/cluster_vis.py
  deepcell_spots/cluster_vis_test.py
  deepcell_spots/decoding_functions.py
  deepcell_spots/decoding_functions_test.py
  deepcell_spots/dotnet.py
  deepcell_spots/dotnet_losses.py
  deepcell_spots/dotnet_losses_test.py
  deepcell_spots/dotnet_test.py
  deepcell_spots/image_alignment.py
  deepcell_spots/image_alignment_test.py
  deepcell_spots/image_generators.py
  deepcell_spots/image_generators_test.py
  deepcell_spots/multiplex.py
  deepcell_spots/multiplex_test.py
  deepcell_spots/point_metrics.py
  deepcell_spots/point_metrics_test.py
  deepcell_spots/simulate_data.py
  deepcell_spots/simulate_data_test.py
  deepcell_spots/singleplex.py
  deepcell_spots/singleplex_test.py
  deepcell_spots/spot_em.py
  deepcell_spots/spot_em_test.py
  deepcell_spots/training.py
  deepcell_spots/utils/__init__.py
  deepcell_spots/utils/augmentation_utils.py
  deepcell_spots/utils/augmentation_utils_test.py
  deepcell_spots/utils/data_utils.py
  deepcell_spots/utils/data_utils_test.py
  deepcell_spots/utils/postprocessing_utils.py
  deepcell_spots/utils/postprocessing_utils_test.py
  deepcell_spots/utils/preprocessing_utils.py
  deepcell_spots/utils/preprocessing_utils_test.py
  deepcell_spots/utils/results_utils.py
  deepcell_spots/utils/results_utils_test.py
  setup.py
Labels: chore
